version: '3.8'

services:

  db:
    container_name: db
    image: postgres:11-alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 15s
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blogs

  fastapi:
    container_name: fastapi
    build: .
    command: bash -c "alembic upgrade head;uvicorn src.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
networks:
  backend:
    driver: bridge
